markdown: kramdown
highlighter: rouge
permalink: /p/:categories/:title/

atom-baseurl: "http://icerdesign.com"

la51_analytics: 17278963
oldarticlenotice:
  formeryear: 2009
  birthyear: 1986

include: ['_pages']

collections:
  questions:
    output: true
    permalink: /:collection/:path/

# highlighter: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      lang: "zh"
  -
    scope:
      type: "questions"
    values:
      layout: "question"
      lang: "en"
      showall: true

plugins:
- jekyll-paginate-v2

pagination:
  enabled: true
  debug: false
  collection: 'questions'
  per_page: 10
  title: ':title - :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 3
    after: 5
