markdown: kramdown
highlighter: rouge
permalink: /p/:categories/:title/

atom-baseurl: "http://blog.wizicer.com"

la51_analytics: 17278963
oldarticlenotice:
  formeryear: 2009
  birthyear: 1986

include: ['_pages']

collections:
  questions:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      lang: "zh"
  -
    scope:
      type: "questions"
    values:
      layout: "question"
      lang: "en"