markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
name: "冰河小站"

author: "冰河魔法师"
atom-baseurl: "http://blog.wizicer.com"

la51_analytics: 17278963
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://hiyaphoto.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

